Enabled -s2e-softmmu targets.
git-svn-id: https://dslabpc10.epfl.ch/svn/src/s2e/trunk@8690 f94e2f5b-dfd8-4992-a279-46519bc7c46e

diff --git a/qemu/configure b/qemu/configure
--- a/qemu/configure
+++ b/qemu/configure
@@ -2359,6 +2359,14 @@ case "$target" in
   ${target_arch2}-softmmu)
     target_softmmu="yes"
     ;;
+  ${target_arch2}-s2e-softmmu)
+    if test "$s2e" != "yes" ; then
+      echo "ERROR: Target '$target' is only available with --enable-s2e"
+      exit 1
+    fi
+    target_softmmu="yes"
+    target_s2e="yes"
+    ;;
   ${target_arch2}-linux-user)
     if test "$linux" != "yes" ; then
       echo "ERROR: Target '$target' is only available on a Linux host"
